// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// MinkowskiSumEK
Rcpp::List MinkowskiSumEK(const Rcpp::List rmesh1, const Rcpp::List rmesh2, const bool triangulate, const bool normals, const bool triangulate1, const bool triangulate2);
RcppExport SEXP _MinkowskiSum_MinkowskiSumEK(SEXP rmesh1SEXP, SEXP rmesh2SEXP, SEXP triangulateSEXP, SEXP normalsSEXP, SEXP triangulate1SEXP, SEXP triangulate2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh1(rmesh1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type rmesh2(rmesh2SEXP);
    Rcpp::traits::input_parameter< const bool >::type triangulate(triangulateSEXP);
    Rcpp::traits::input_parameter< const bool >::type normals(normalsSEXP);
    Rcpp::traits::input_parameter< const bool >::type triangulate1(triangulate1SEXP);
    Rcpp::traits::input_parameter< const bool >::type triangulate2(triangulate2SEXP);
    rcpp_result_gen = Rcpp::wrap(MinkowskiSumEK(rmesh1, rmesh2, triangulate, normals, triangulate1, triangulate2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MinkowskiSum_MinkowskiSumEK", (DL_FUNC) &_MinkowskiSum_MinkowskiSumEK, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_MinkowskiSum(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
